from pathlib import Path
import re
p=Path('www/index.html')
s=p.read_text(encoding='utf-8')

pat=re.compile(r'''  var segments = \[.*?\n  \];\n  var wheelColors = \[.*?\];\n  var wheelColorsDark = \[.*?\];\n  var wheelLabelColors = \[.*?\];''',re.S)
rep=r'''  var segments = [
    {key:"avocat",name:"Avocat / Guacamole",emoji:"🥑",type:"ingredient"},{key:"piment",name:"Piment / Salsa",emoji:"🌶️",type:"ingredient"},{key:"tortilla",name:"Tortilla / Nachos",emoji:"🌮",type:"ingredient"},{key:"fromage",name:"Fromage / Queso",emoji:"🧀",type:"ingredient"},{key:"viande",name:"Viande / Haricots",emoji:"🍖",type:"ingredient"},{key:"epice",name:"Épice Mystère",emoji:"✨",type:"mystere"},{key:"coin",name:"Pièce Mexico",emoji:"🪙",type:"coin"},{key:"memory",name:"Mémoire Duel",emoji:"🃏",type:"memory"},{key:"bonus",name:"Panier Surprise",emoji:"🎁",type:"bonus"},{key:"exchange",name:"Échange Fiesta",emoji:"🔄",type:"exchange"},{key:"bomb",name:"Explosif",emoji:"💣",type:"bomb"},{key:"lightning",name:"Éclair Turbo",emoji:"⚡",type:"lightning"},{key:"mask",name:"Masque Mexicain",emoji:"🎭",type:"mask"}
  ];
  var wheelColors=["#5B7B3F","#C6401F","#E8A33D","#F2D06B","#B85C38","#7A3B8C","#0B7C71","#B33B66","#D49B22","#3C78A8","#6B2523","#E7B52C","#116C65"];
  var wheelColorsDark=["#4A6432","#9E2E17","#C4831C","#D9AD3A","#96492C","#5F2E70","#07564F","#812847","#A97615","#295477","#3B1110","#A8780C","#084A45"];
  var wheelLabelColors=["#fff","#fff","#3a2a12","#3a2a12","#fff","#fff","#fff","#fff","#3a2a12","#fff","#fff","#35240a","#fff"];'''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 segments not found')

pat=re.compile(r'''  function pickWheelIndex\(state\)\{.*?\n  \}\n\n  function spinWheelEl''',re.S)
rep=r'''  function pickWheelIndex(state){state.history=state.history||[];var w=segments.map(function(seg,i){var x=1;if(seg.type==="mystere")x=.78;if(seg.type==="coin")x=.68;if(seg.type==="memory")x=.62;if(seg.type==="bonus")x=.56;if(seg.type==="exchange")x=.54;if(seg.type==="bomb")x=.28;if(seg.type==="lightning")x=.42;if(seg.type==="mask")x=.30;if(state.history[0]===i)x*=.05;if(state.history[1]===i)x*=.34;return x*(.86+Math.random()*.28)}),t=w.reduce(function(a,b){return a+b},0),r=Math.random()*t,idx=0;for(var i=0;i<w.length;i++){r-=w[i];if(r<=0){idx=i;break}}state.history.unshift(idx);if(state.history.length>5)state.history.length=5;return idx}

  function spinWheelEl'''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 picker not found')

s=s.replace('<span><b>🔄</b>Échange</span></div>','<span><b>🔄</b>Échange</span><span><b>💣</b>Explosif</span><span><b>⚡</b>Éclair</span><span><b>🎭</b>Masque</span></div>')
pat=re.compile(r'''      var tip=seg\.type==="ingredient"\?.*?;\n      wheelResult\.innerHTML=''',re.S)
rep=r'''      var tips={ingredient:"Pioche l’ingrédient.",mystere:"Coup de Piment !",coin:"Pièce Mexico.",memory:"Mémoire Duel : premier à 3 paires = 1 recette.",bonus:"Gagne un ingrédient.",exchange:"Échange Fiesta.",bomb:"Perds une recette validée.",lightning:"La roue accélère : appuie sur RALENTIR.",mask:"Gagne une recette complète."};var tip=tips[seg.type]||"Événement Fiesta !";
      wheelResult.innerHTML='''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 standalone tip not found')

css=r'''<style id="tf-v9-gameplay">.tf-v9-special{text-align:center;padding:8px}.tf-v9-special .big{font-size:3.5rem}.tf-v9-special h3{font-family:Georgia,serif;color:#8f2e21}.tf-memory-duel-score{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;padding:9px;margin-bottom:10px;border-radius:16px;background:#fff5dc}.tf-memory-duel-score .side{text-align:center;font-weight:900}.tf-memory-duel-score .pts{display:block;color:#087267;font-size:1.15rem}.tf-memory-turn{text-align:center;font-weight:900;color:#9e2c1f;margin:6px}.tf-memory-turn.ai{color:#087267}.tf-turbo-panel{display:none;margin:10px auto;padding:12px;width:min(92%,390px);border-radius:18px;background:linear-gradient(135deg,#fff2a8,#ffd052);border:2px solid #a76f08;text-align:center}.tf-turbo-panel.show{display:block;animation:tfTG .35s ease-in-out infinite alternate}.tf-turbo-brake{width:100%;border:0;border-radius:14px;padding:13px;background:#b62820;color:#fff;font-weight:950;font-size:1rem}.tf-turbo-wheel{filter:drop-shadow(0 0 13px rgba(255,201,27,.8))}@keyframes tfTG{from{transform:scale(.99)}to{transform:scale(1.015)}}</style>'''
if 'id="tf-v9-gameplay"' not in s:s=s.replace('</head>',css+'\n</head>',1)

pat=re.compile(r'''  function tfExchangeFiesta\(player,opponent\)\{.*?\n\n  function tfBuildWheelCoinHTML''',re.S)
rep=r'''  function tfExchangeFiesta(player,opponent){var a=tfOwnedIngredientKeys(player),b=tfOwnedIngredientKeys(opponent),pairs=[];a.forEach(function(ka){b.forEach(function(kb){if(ka!==kb)pairs.push([ka,kb])})});if(!pairs.length){var g=tfGiveRandomIngredient(player);return "Échange impossible : bonus "+g.emoji+" "+g.label+"."}var z=pairs[Math.floor(Math.random()*pairs.length)],ka=z[0],kb=z[1];player.hand[ka]--;opponent.hand[kb]--;player.hand[kb]=(player.hand[kb]||0)+1;opponent.hand[ka]=(opponent.hand[ka]||0)+1;return player.name+" donne "+tfIngredientEmoji(ka)+" "+ING[ka].label+" et reçoit "+tfIngredientEmoji(kb)+" "+ING[kb].label+"."}
  function tfAwardCompleteRecipe(i,source){var p=game.players[i],r=null;if(p.recipes.length)r=p.recipes.splice(Math.floor(Math.random()*p.recipes.length),1)[0];else if(game.deck.length)r=game.deck.pop();if(!r)return null;p.validated.push(r);if(game.deck.length)p.recipes.push(game.deck.pop());showToast("🏆 "+p.name+" gagne « "+r.name+" » !",3200);tfSpeak(p.name+" gagne une recette complète grâce à "+source);if(p.validated.length>=3){game.status="ended";game.winnerIdx=i}return r}
  function tfLoseCompleteRecipe(i){var p=game.players[i];if(!p.validated.length)return{lost:null,eliminated:false};var r=p.validated.splice(Math.floor(Math.random()*p.validated.length),1)[0];game.deck=shuffle(game.deck.concat([r]));var e=p.validated.length===0;if(e){p.eliminated=true;game.status="ended";game.winnerIdx=1-i}return{lost:r,eliminated:e}}
  function tfShowSpecial(title,emoji,html,done){openModal(title,'<div class="tf-v9-special"><div class="big">'+emoji+'</div>'+html+'</div>',function(){setTimeout(function(){closeModal();if(done)done()},1800)})}
  function tfRunExchange(i,done){var p=game.players[i],o=game.players[1-i],m=tfExchangeFiesta(p,o);tfSpeak("Échange Fiesta");tfShowSpecial("🔄 Échange Fiesta","🔄",'<h3>Échange effectué</h3><p>'+m+'</p>',function(){renderGame();done()})}

  function tfBuildWheelCoinHTML'''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 exchange helper block not found')

pat=re.compile(r'''  function tfMemoryDeck\(\)\{.*?\n\n  /\* ---------- Coup de Piment resolution ---------- \*/''',re.S)
rep=r'''  function tfMemoryDeck(){var k=tfNormalIngredientKeys().slice(),c=[];while(c.length<4)c.push(k.splice(Math.floor(Math.random()*k.length),1)[0]);return shuffle(c.concat(c).map(function(x,i){return{key:x,id:x+"-"+i}}))}
  function tfBuildMemoryDuelHTML(starter){var d=tfMemoryDeck();window.tfMemoryDuel={deck:d,seen:{},sel:[],scores:[0,0],turn:starter,busy:false,finished:false};var a=game.players[0],b=game.players[1],h='<div class="tf-memory-duel-score"><div class="side">'+a.avatar+' '+a.name+'<span class="pts" id="tfMemScore0">0 paire</span></div><b>VS</b><div class="side">'+b.avatar+' '+b.name+'<span class="pts" id="tfMemScore1">0 paire</span></div></div><div class="tf-memory-turn" id="tfMemoryTurn"></div><div class="tf-memory-grid">';d.forEach(function(x,i){h+='<button class="tf-memory-card" data-memory-index="'+i+'"><span class="tf-card-back">🌵</span><span class="tf-card-front">'+tfIngredientEmoji(x.key)+'</span></button>'});return h+'</div><div class="modal-result" id="tfMemoryResult">Premier à 3 paires = 1 recette complète.</div>'}
  function tfRunMemory(starter,done){openModal("🃏 Mémoire Duel",tfBuildMemoryDuelHTML(starter),function(){var st=window.tfMemoryDuel,cards=document.querySelectorAll("#modalBody .tf-memory-card"),res=document.getElementById("tfMemoryResult"),turn=document.getElementById("tfMemoryTurn");function avail(){var x=[];cards.forEach(function(c,i){if(!c.classList.contains("matched"))x.push(i)});return x}function upd(){for(var i=0;i<2;i++){var e=document.getElementById("tfMemScore"+i);if(e)e.textContent=st.scores[i]+(st.scores[i]>1?" paires":" paire")}var p=game.players[st.turn];turn.textContent=(p.isAI?"🤖 ":"👉 ")+"Au tour de "+p.name;turn.classList.toggle("ai",p.isAI)}function reveal(i){if(st.busy||st.finished||cards[i].classList.contains("matched")||cards[i].classList.contains("open"))return false;cards[i].classList.add("open");st.seen[i]=st.deck[i].key;st.sel.push(i);return true}function finish(i){if(st.finished)return;st.finished=true;st.busy=true;cards.forEach(function(c){c.disabled=true});var r=tfAwardCompleteRecipe(i,"Mémoire Duel");res.innerHTML='🏆 <strong>'+game.players[i].name+' gagne !</strong><br>'+(r?'Recette : '+r.name:'');setTimeout(function(){closeModal();renderGame();done()},1800)}function resolve(a,b){st.busy=true;setTimeout(function(){var ok=st.deck[a].key===st.deck[b].key;if(ok){cards[a].classList.add("matched");cards[b].classList.add("matched");st.scores[st.turn]++;res.textContent="✅ Paire pour "+game.players[st.turn].name}else{cards[a].classList.remove("open");cards[b].classList.remove("open");st.turn=1-st.turn;res.textContent="❌ Raté : joueur suivant"}st.sel=[];st.busy=false;upd();if(st.scores[0]>=3)finish(0);else if(st.scores[1]>=3)finish(1);else sched()},620)}function known(){var a=avail();for(var x=0;x<a.length;x++)for(var y=x+1;y<a.length;y++)if(st.seen[a[x]]&&st.seen[a[x]]===st.seen[a[y]])return[a[x],a[y]];return null}function rnd(ex){var a=avail().filter(function(i){return ex.indexOf(i)<0});return a.length?a[Math.floor(Math.random()*a.length)]:-1}function ai(){if(st.finished||st.busy||!game.players[st.turn].isAI)return;var p=known();if(p){reveal(p[0]);setTimeout(function(){reveal(p[1]);resolve(p[0],p[1])},430);return}var a=rnd([]);if(a<0)return;reveal(a);setTimeout(function(){var m=avail().filter(function(i){return i!==a&&st.seen[i]===st.deck[a].key}),b=m.length?m[0]:rnd([a]);if(b>=0){reveal(b);resolve(a,b)}},520)}function sched(){upd();if(game.players[st.turn].isAI)setTimeout(ai,700)}cards.forEach(function(c){c.addEventListener("click",function(){if(st.busy||st.finished||game.players[st.turn].isAI)return;var i=Number(c.dataset.memoryIndex);if(reveal(i)&&st.sel.length===2)resolve(st.sel[0],st.sel[1])})});sched()})}
  function tfEnsureTurboPanel(){var p=document.getElementById("tfTurboPanel");if(p)return p;var b=document.getElementById("wheelStickyBox");if(!b)return null;p=document.createElement("div");p.id="tfTurboPanel";p.className="tf-turbo-panel";p.innerHTML='<strong id="tfTurboText">⚡ Éclair Turbo !</strong><button class="tf-turbo-brake" id="tfTurboBrake">⚡ RALENTIR</button>';b.appendChild(p);return p}
  function tfRunLightning(i){var pl=game.players[i],svg=document.getElementById("gameWheel"),panel=tfEnsureTurboPanel(),btn=document.getElementById("tfTurboBrake"),txt=document.getElementById("tfTurboText"),holder=svg&&svg.closest?svg.closest(".wheel-holder"):null;if(!svg||!panel||!btn){afterSpinUpdate();return}var box=document.getElementById("wheelStickyBox");if(box)box.classList.remove("collapsed");try{box.scrollIntoView({behavior:"smooth",block:"center"})}catch(e){}panel.classList.add("show");btn.disabled=pl.isAI;btn.textContent=pl.isAI?"🤖 L’IA va ralentir…":"⚡ RALENTIR";txt.textContent="⚡ La roue accélère de plus en plus…";if(holder)holder.classList.add("tf-turbo-wheel");tfSpeak("Éclair Turbo, la roue accélère");var ang=gameWheelState.rotation||0,last=performance.now(),speed=.72,run=true,raf=0;svg.style.transition="none";function frame(t){if(!run)return;var d=Math.min(34,t-last);last=t;speed=Math.min(1.65,speed+d*.00032);ang+=speed*d;svg.style.transform="rotate("+ang+"deg)";raf=requestAnimationFrame(frame)}function brake(){if(!run)return;run=false;cancelAnimationFrame(raf);btn.disabled=true;btn.textContent=pl.isAI?"🤖 RALENTI !":"✅ RALENTI !";var sl=360/segments.length,base=ang+230+speed*120+Math.random()*100,m=((base%360)+360)%360,idx=Math.floor((((360-m)%360+360)%360)/sl)%segments.length;if(segments[idx].type==="lightning")idx=(idx+1)%segments.length;var des=((360-(idx*sl+sl/2))%360+360)%360,bm=((base%360)+360)%360,fin=base+((des-bm+360)%360);gameWheelState.rotation=fin;svg.style.transition="transform 2200ms cubic-bezier(.10,.78,.18,1)";svg.style.transform="rotate("+fin+"deg)";duckMusicFor(2200);setTimeout(function(){if(holder)holder.classList.remove("tf-turbo-wheel");panel.classList.remove("show");var sg=segments[idx],e=document.getElementById("flipEmoji"),l=document.getElementById("flipLabel"),c=document.getElementById("drawFlipCard");if(e)e.textContent=sg.emoji;if(l)l.textContent=sg.name;if(c)c.classList.add("flipped");setTimeout(function(){handleSpinResult(idx)},500)},2250)}btn.onclick=brake;raf=requestAnimationFrame(frame);setTimeout(brake,pl.isAI?1100+Math.random()*1500:5200)}

  /* ---------- Coup de Piment resolution ---------- */'''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 memory block not found')

pat=re.compile(r'''  function handleSpinResult\(idx\)\{.*?\n  \}\n\n  var gameWheelEl =''',re.S)
rep=r'''  function handleSpinResult(idx){var seg=segments[idx],p=game.players[game.turn],o=game.players[1-game.turn];game.hasSpun=true;tfSayWheel(seg,p);if(seg.type==="ingredient"||seg.type==="mystere"){p.hand[seg.key]=(p.hand[seg.key]||0)+1;if(p.isAI)showToast("🤖 "+p.name+" pioche "+seg.emoji+" "+ING[seg.key].label);setTimeout(function(){if(seg.key==="epice")resolveCoupDePiment(game.turn,1-game.turn,afterSpinUpdate);else afterSpinUpdate()},1050);return}if(seg.type==="coin"){setTimeout(function(){tfRunWheelCoin(game.turn,afterSpinUpdate)},500);return}if(seg.type==="memory"){setTimeout(function(){tfRunMemory(game.turn,afterSpinUpdate)},500);return}if(seg.type==="bonus"){var g=tfGiveRandomIngredient(p);showToast("🎁 +1 "+g.emoji+" "+g.label,2600);setTimeout(afterSpinUpdate,900);return}if(seg.type==="exchange"){setTimeout(function(){tfRunExchange(game.turn,afterSpinUpdate)},350);return}if(seg.type==="mask"){var r=tfAwardCompleteRecipe(game.turn,"Masque Mexicain");tfShowSpecial("🎭 Masque Mexicain","🎭",'<h3>Recette offerte !</h3><p>'+(r?p.name+' gagne <strong>'+r.name+'</strong>.':'Aucune recette disponible.')+'</p>',function(){renderGame();afterSpinUpdate()});return}if(seg.type==="bomb"){var b=tfLoseCompleteRecipe(game.turn),m=!b.lost?p.name+" n’a aucune recette à perdre.":b.eliminated?p.name+" perd <strong>"+b.lost.name+"</strong> et sa dernière recette : <strong>éliminé !</strong>":p.name+" perd <strong>"+b.lost.name+"</strong>.";tfShowSpecial("💣 EXPLOSIF !","💥",'<h3>BOUM !</h3><p>'+m+'</p>',function(){renderGame();afterSpinUpdate()});return}if(seg.type==="lightning"){setTimeout(function(){tfRunLightning(game.turn)},400);return}setTimeout(afterSpinUpdate,500)}

  var gameWheelEl ='''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('V9 handleSpinResult not found')

s=s.replace('roue Fiesta, Pièce Mexico, Mémoire Mexico et recettes à cuisiner.','roue Fiesta, Mémoire Duel, Éclair Turbo, Explosif, Masque Mexicain et recettes à cuisiner.')
need=['type:"bomb"','type:"lightning"','type:"mask"','tfAwardCompleteRecipe','tfLoseCompleteRecipe','Premier à 3','tfRunLightning','tfRunExchange','if(seg.type==="ingredient"||seg.type==="mystere")','function runAiTurn()']
miss=[x for x in need if x not in s]
if miss:raise SystemExit('V9 validation: '+','.join(miss))
p.write_text(s,encoding='utf-8')
print('V9 gameplay OK')